version: '3'

services:
  php:
    image: php:apache
    ports:
      - 8000:8000
    volumes:
      - ./php/www:/var/www/html/

  node:
    image: node
    working_dir: ./Knt-Manager
    environment:
      - NODE_ENV=debug
    ports:
      - 8000:8000
    command: "npm run watch"